from __future__ import annotations

TITLE_VAR = "n5ZHYrj8"
EPISODE_WORD_COUNT_VAR = "eBEWC07Q"
TOTAL_EPISODES_VAR = "blkSS7dY"
STORY_OUTLINE_VAR = "ayxWwSpE"
CORE_SCENE_INPUT_VAR = "rxmvq2lS"
CHARACTER_BIOS_VAR = "yYYOuumm"
EPISODE_PLAN_VAR = "pxtQY7p2"

WORLDVIEW_RETRY_VAR = "rXkPrri4"
WORLDVIEW_VAR = "yuozoGpo"
WORLDVIEW_MAX_RETRY_VAR = "zU2iiFNA"

SCENE_VAR = "iJudZHhM"
SCENE_RETRY_VAR = "unv7xO72"
SCENE_MAX_RETRY_VAR = "uCB2VKwo"

CHARACTER_VAR = "fFM0mroW"
CHARACTER_RETRY_VAR = "d9g8vngS"
CHARACTER_MAX_RETRY_VAR = "h3fAdn6f"

HOOK_START_VAR = "iJkq6iGe"
HOOK_CURRENT_VAR = "nIGPvKG2"
HOOK_RETRY_VAR = "zkzVCtkm"
HOOK_MAX_RETRY_VAR = "jMy88hKE"

DIALOGUE_START_VAR = "sKq9Iyza"
DIALOGUE_CURRENT_VAR = "mN7Fh38L"
DIALOGUE_RETRY_VAR = "llKW3OVX"
DIALOGUE_MAX_RETRY_VAR = "mQFrT0Al"

SCRIPT_START_VAR = "d4sfifeZ"
SCRIPT_CURRENT_VAR = "zS2LXibg"
SCRIPT_RETRY_VAR = "nCZK9S2O"
SCRIPT_MAX_RETRY_VAR = "essitQMV"

CORE_SCENE_FINAL_VAR = "fuKbtNtY"
HOOK_FINAL_VAR = "hUoaaRhJ"
DIALOGUE_FINAL_VAR = "pS7JzosX"
SCRIPT_FINAL_VAR = "vI8t3a31"
MEMORY_VAR = "dzt6kORx"

EPISODE_CONSISTENCY_NODE_ID = "nQPgHXSPN8TgK1am"
EPISODE_CONSISTENCY_FAILURE_NODE_ID = "soUW8KsdGduKMGpv"
FINAL_TEXT_EDITOR_NODE_ID = "gRGu2yeKM1MwfKBM"
FINAL_ANSWER_NODE_ID = "jXRpfvNMxP4oj9dD"
